---
- name: Fail when pgagent_database is not present
  fail:
    msg: "Variable pgagent_database is required"
  when: pgagent_database is not defined or pgagent_database|length == 0

- name: Install pgagent apt package
  apt:
    name: pgagent
    update_cache: yes
    state: "{{ pgagent_upgrade | ternary('latest', 'present', 'present') }}"
  register: apt_pkg
  notify: restart pgagent

- name: Create common pg_env variable
  no_log: true
  set_fact:
    pg_env: >-
      {{ pg_env | default({}) | combine ({ item.key : item.value }) }}
    is_remote_host: >-
      {{ pgagent_hostaddr is defined and pgagent_hostaddr|length > 0 }}
    has_password: >-
      {{ pgagent_password is defined and pgagent_password|length > 0 }}
    no_postgres_user: "{{ pgagent_user != 'postgres' }}"
  with_items:
    - {'key': 'PGDATABASE', 'value': "{{ pgagent_database }}"}
    - {'key': 'PGPORT', 'value': "{{ pgagent_database_port }}"}

- name: Add PGUSER if it is different to postgres
  set_fact:
    pg_env: "{{ pg_env | combine ({ item.key : item.value }) }}"
  with_items:
    - {'key': 'PGUSER', 'value': "{{ pgagent_user }}"}
  when: no_postgres_user

- name: Add PGPASSWORD if it is defined and not empty
  set_fact:
    pg_env: "{{ pg_env | combine ({ item.key : item.value }) }}"
  with_items:
    - {'key': 'PGPASSWORD', 'value': "{{ pgagent_password }}"}
  when: has_password

- name: Add PGHOST if it is defined and not empty
  set_fact:
    pg_env: "{{ pg_env | combine ({ item.key : item.value }) }}"
  with_items:
    - {'key': 'PGHOST', 'value': "{{ pgagent_hostaddr }}"}
  when: is_remote_host

- name: Create extension in the target database
  command: >-
    psql -c "CREATE EXTENSION IF NOT EXISTS pgagent"
  register: create_extension
  become_user: postgres
  environment: "{{ pg_env }}"
  become: yes
  changed_when: >-
    'already exists' not in create_extension.stderr
  notify: restart pgagent

- name: Update extension in the target database
  command: >-
    psql -c "ALTER EXTENSION pgagent UPDATE;"
  environment: "{{ pg_env }}"
  register: update_extension
  become_user: postgres
  become: yes
  notify: restart pgagent
  changed_when: >-
    'already installed' not in update_extension.stderr
  when: pgagent_upgrade and apt_pkg.changed

- name: Create a directory for env variables
  file:
    path: /etc/pgagent
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: Create env file
  template:
    src: templates/env.conf
    dest: /etc/pgagent/{{ pgagent_database }}.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart pgagent

- name: Create log entries for pgAgent unit
  file:
    path: /var/log/pgagent
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'

- name: Set up logrotate entry for pgagent unit
  copy:
    src: files/pgagent.logrotate
    dest: /etc/logrotate.d/pgagent
    owner: root
    group: root
    mode: 0644

- name: Copy pgAgent template unit into /etc/systemd/system/pgagent@.service
  template:
    src: templates/pgagent@.service
    dest: /etc/systemd/system/pgagent@.service
    owner: root
    group: root
    mode: '0644'
  notify: restart pgagent
