---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    pgagent_database: pgagent_test_db
  tasks:

    - name: force all notified handlers
      meta: flush_handlers

    - name: Check pgagent is started
      systemd:
        name: "pgagent@{{ pgagent_database }}"
        state: started
        enabled: yes
        daemon_reload: yes
